local rules = {}

table.insert(rules, {
  { 0x14, "*Z[?#]*", "" },
  { 0x00, "*`no`<APNw#?\"'>[,*]", "@y" },
  { 0x3F, "*~<UVXY>Z*", "" },
  { 0x04, "*T\"<$>\"NZ*", "@@\"$^NV" },
  { 0x00, "*VX", "@N" },
  { 0x00, "*Z:", "@N" },
  { 0x00, "*Ze", "@NN" },
  { 0x00, "*X`there`", "@f " },
  { 0x0A, "*[EeG]*", "" },
  { 0x0A, "*<S>Z<HI:>*", "" },
  { 0x02, "*SZ", "" },
  { 0x0B, "*[TO]~<XYVU>B`be`", "" },
  { 0x0B, "*#-ZCZEP", "" },
  { 0x01, "*<DK,>Z[TAO]", "@$V" },
  { 0x00, "*~<UVXY>ZT", "@$V" },
  { 0x0B, "*~<RQJUVXYB,C>[yVUXY]", "" },
  { 0x07, "*e<\"'>[DpbTOSN]", "@V" },
  { 0x01, "*<DK,>Z~[,CbUYXVPZ*]", "@$V" },
  { 0x00, "*ZZP", "@V" },
  { 0x00, "*Z<,CZ>M", "@V" },
  { 0x00, "*<dD,>B<dD>[VZ]<$>,", "@$J$V$j" },
  { 0x00, "*<dD,>B<dD>Y<$>,", "@$J$Y$j" },
  { 0x0C, "*<dD,>B[VZ]<$>R[UVXY]", "" },
  { 0x00, "*<dD,>`assuming`R<$>,~C", "@$JR$j" },
  { 0x00, "*<dDC,>`let`", "@$V" },
  { 0x06, "*`as`<$>,", "@J$;" },
  { 0x00, "*<dD,>`if`~<,>`then`", "@$J$j" },
  { 0x00, "*<dD,>`if`<$>,~C", "@$J$j" },
  { 0x00, "*<dD,>j<$>,~C", "@$J$;" },
  { 0x00, "*<dD,>`when`<$>,~C", "@$J$j" },
  { 0x00, "*<dD,>`during`<$>,", "@$P$j" },
  { 0x00, "*<dD,>`since`~<(>,", "@$J$j" },
  { 0x0E, "*<CdD,>P~<VXYU>,", "@$P$;" },
  { 0x00, "*pG,", "@PNj" },
  { 0x00, "*GPH,[TORS]", "@gPHj" },
  { 0x00, "*p~<VXY>,", "@P$j" },
  { 0x00, "*p<$>,", "@J$j" },
  { 0x0F, "*<dD,>JG~<,>R", "" },
  { 0x00, "*y~<VXY>,C", "@@$j" },
  { 0x03, "*[?#]<-KdD>Z~[UVXYxy]", "@#$V" },
  { 0x03, "*[?#](~<UVXYxy>)Z~[UVXYxy]", "@#($)V" },
  { 0x04, "*NZN<GFNwPDA>[,(*]", "@@V" },
  { 0x04, "*TZZ<dD>[,(J*]", "@@NV" },
  { 0x05, "*~<XYVZEe>NZ<dD>[THI*]", "" },
  { 0x05, "*<STAOIH>N<wdD>Z~<eEbXYV>[(,QRS*]", "" },
  { 0x00, "*[NG]XB", "@NU " },
  { 0x06, "*G[C,JPp]", "@N" },
})

table.insert(rules, {
  { 0x3A, "`a`[:*)]", "#" },
  { 0x3A, "[\"']`a`[\"']", ".#" },
  { 0x00, "\"<$>,\"", "|$,=" },
  { 0x2A, "-", "^" },
  { 0x00, "(#)", "{#}" },
  { 0x00, "_Z[_*]", "@N" },
  { 0x00, "`please`[VZ]", "jV" },
  { 0x00, "aG", "@A" },
  { 0x00, "bG", "BV" },
  { 0x00, "aZN", "@A" },
  { 0x00, "T<H%D,>Z", "@$N" },
  { 0x00, "Z[bY{]", "N" },
  { 0x00, "Z[AE]`by`", "N" },
  { 0x32, "UR<KdD>[VZ]", "@@$V" },
  { 0x32, "UR`do`", "@" },
  { 0x32, "U<TAO>N<Nw>[XY]", "@" },
  { 0x33, "[XY]<K>R[eE]", "" },
  { 0x34, "[XY]KR", "" },
  { 0x36, "X~<xyUVXYB>`be`", "" },
  { 0x00, "[RbKk]<D>Z", ".$V" },
  { 0x00, "U<KdD>Z", "@$V" },
  { 0x00, "NZ`how`", "@V" },
  { 0x00, "`others`Z", "SV" },
  { 0x00, "X`busy`G", "@ G" },
  { 0x00, "[=,]`said`", "=V" },
  { 0x39, "N[Gx]", "@N" },
  { 0x00, "i[dA]", "aA" },
  { 0x00, "HCa", "@@i" },
  { 0x00, "A`one`", "@s" },
  { 0x00, "`trouble`G", "Ng" },
  { 0x00, "`troubles`G", "Ng" },
  { 0x00, ",`say`,", "@D" },
  { 0x00, "P`may`[,*]", "@N" },
  { 0x00, "[VE]`as`<DE>G", ".D$F" },
  { 0x00, "B[THIE]", "P" },
  { 0x03, "B<DE>G", "P$N" },
  { 0x02, "[^TAOp]<DE>G", "" },
  { 0x03, "`if`G", "PN" },
  { 0x07, "BZ", "PN" },
  { 0x07, "IZ", "@N" },
  { 0x00, "[PB]SZ", "PON" },
  { 0x00, "ESZ", "@@N" },
  { 0x00, "B<IH\"-/?>[AOSN#]", "P" },
  { 0x01, "[bB]Z[TAOEGHI]", ".V" },
  { 0x00, "[,C]<KD\"'>Z[TAO#M]", ".$V" },
  { 0x00, "~[HI],Z[HI]", ".,V" },
  { 0x00, "~[QJ]ZR", ".V" },
  { 0x3B, "[fTAOSN#GJjZ]~<QJLBR>[UVXY]", "" },
  { 0x3C, "[UVXY]~<UVXY>[R|;^*]", "" },
  { 0x0A, "Y<dDK>`pleasure``in`G", "@$NbV" },
  { 0x17, "Y`been`G", "  V" },
  { 0x21, "[Rk]<D>e", ".$V" },
  { 0x00, "e`without`", "N" },
  { 0x2F, "[TPAOV]<dD,C\"'>E~*", ".$A" },
  { 0x00, "`been`e", "EE" },
  { 0x00, "[fxyTOP|]<dDAOSIH>Z", ".$N" },
  { 0x00, ";<dDAOSIH>Z~<UVXYxy>[J,C*]", "@$V" },
  { 0x00, "[yVTAOP|;]<dDAOSIH>x", ".$N" },
  { 0x1F, "N`of`G", "@bV" },
  { 0x00, "Z<->`of`", "N" },
  { 0x03, "G<->`of`", "N" },
  { 0x02, "~A`of`G", "" },
  { 0x02, "GG", "" },
  { 0x02, "[|;T]<adAE\"'>G", "" },
  { 0x03, "G-N", "N N" },
  { 0x03, "N-G", "@ N" },
  { 0x00, "G-P", "N-P" },
  { 0x00, "[N#P]-Z", ".-N" },
  { 0x00, "NCZ<K>[(B]", "@@N" },
  { 0x38, "N<w>[dD]Z", "@$.V" },
  { 0x00, "Q<AZNw>B[VZ]", "@$bV" },
  { 0x00, "[NZ]<(w?#)>`who`<dD>Z", "N$L$V" },
  { 0x00, "[TPO]<a>d~[GIH]", ".$A" },
  { 0x00, "NXd[*,]", "@@A" },
  { 0x00, "[H?#NZ]-`based`", "A  " },
  { 0x00, "A-A-N", "@ @ " },
  { 0x2C, "[dD]-B-[ZV]", "D   A" },
  { 0x00, "A-[?#]-Z", "@ . N" },
  { 0x00, "[#?H]-[NIAZ]", "A-A" },
  { 0x09, "I-N", "@-A" },
  { 0x00, "[?#N]-A", "A A" },
  { 0x00, "N-e", "@-N" },
  { 0x0F, "`it`X<KD>d", "  " },
  { 0x05, "`it``being`<KdD>E", "  $V" },
  { 0x06, "XdZ", "@DV" },
  { 0x06, "X<KdD>e", "@$V" },
  { 0x00, "XAV", "@D" },
  { 0x00, "XK,", " D" },
  { 0x00, "XU", " " },
  { 0x00, "PU", "D" },
  { 0x00, "[XY]AEP", ".D" },
  { 0x00, "[UB]`do`", ".V" },
  { 0x00, "`suggest`R[VZe]", "VMV" },
  { 0x13, "`which`[ZEe]T", "SV" },
  { 0x23, "`could`Y[Ee]", "  V" },
  { 0x00, "`may`<KdD>XG", "d" },
  { 0x00, "`may`<KdD>[UY]~[AO]", "d" },
  { 0x00, "`must`<KdD>Y[Ee]", "d$YE" },
  { 0x00, "`must`<KdD>XG", "d" },
  { 0x1D, "`do`K`be`E", " K V" },
  { 0x00, "Ry", "r" },
  { 0x1B, "RY[TAOSHI]", "" },
  { 0x0D, "XB`be`E", "U X" },
  { 0x0D, "BXEJ", "U" },
  { 0x00, "U<KdD>X`able`B[ZV]", "@$   V" },
  { 0x0A, "U<KAdD,'\">[ZV]", "@$V" },
  { 0x0B, "U<KAdD?'\">X<AdD'\">[Ee]", "@$ $V" },
  { 0x0B, "U<PINw>X<AdD'\">[Ee]", "@$ $V" },
  { 0x0C, "BYE", "@ V" },
  { 0x0C, "UYE", "@ V" },
  { 0x00, "UBX", "@ X" },
  { 0x10, "YE<D>[Ee]", "  $V" },
  { 0x19, "X<KdDu'\">[ZVe]", " $V" },
  { 0x19, "X<KdDu'\">`like`", " $V" },
  { 0x00, "Y<KAdD,'\">e", "@$E" },
  { 0x2D, "U<KAdD?'\">e", "@$V" },
  { 0x2D, "[bB]e", ".V" },
  { 0x12, "e[TAON]", "V" },
  { 0x2D, "V<TPAONw>Ce", "@$CV" },
  { 0x00, "e", "E" },
  { 0x00, "RVBY[ZV]", "@@@ V" },
  { 0x00, "PV", "@N" },
  { 0x00, "T<AO?IH/>[VZ]", "@$N" },
  { 0x00, "\"NV\"", "\"NN" },
  { 0x14, "XYEE", "   V" },
  { 0x14, "Y<KdD?'\">EE", " $ V" },
  { 0x15, "XYEG", "   V" },
  { 0x31, "X<KdD'\">X<dD'\">E", " $ $v" },
  { 0x15, "X<KdD'\">X<dD'\">[GE]", " $ $V" },
  { 0x1F, "NBXE", "@b V" },
  { 0x16, "XGE", "  V" },
  { 0x17, "X<KkdD'\">G", " $V" },
  { 0x17, "XEC<KkdD'\">G", "@@@$V" },
  { 0x18, "X<Kku>YE", " $ V" },
  { 0x18, "Y<CKkdD,'\">E", " $V" },
  { 0x18, "X<CKkdDu'\"R>[ZV]", " $V" },
  { 0x30, "X<KkdD?'\">E", "" },
  { 0x1A, "X<CKkdDI?(,'\")>E", " $V" },
  { 0x1C, "^<KkdDI?(,'\")>E", "" },
  { 0x16, "KXkDE", "@ DV" },
  { 0x1E, "X<KkD>Y", "@" },
  { 0x1E, "X<KkdD,>X", "@$ " },
  { 0x0E, "KE", "" },
  { 0x08, "V`itself`", "@ " },
  { 0x08, "V`ourselves`", "@ " },
  { 0x2B, "R<dD?#>E", "@$V" },
  { 0x00, ",`then`", ",C" },
  { 0x20, "NPTAs", "@@@@N" },
  { 0x0C, "N<wK>B`be`E", "@$LUV" },
  { 0x00, "[NSs#]<,w{}(-HP)\"'>B`be`E", ".$  F" },
  { 0x00, "Z<K(){}-HP>B`be`E", "N$  F" },
  { 0x0C, "N<w>(<$>)<K>B`be`E", "@$($)$LUV" },
  { 0x29, "N<w>B`be`A", "@$ X" },
  { 0x00, "VB`be`EP", "@D A" },
  { 0x00, "`make`[MR]Z", "`заставлять`MV" },
  { 0x3D, "[fxyXYV]~<VXUY>[BbjJLlQ*]", "" },
  { 0x26, "`whether`<TDAOERNw?#'\">[XYUV]", "J" },
})

table.insert(rules, {
  { 0x0000, "=~<)>,", "@$|" },
  { 0x0000, "UP<$>|Z", "@@$|V" },
  { 0x0000, ",`if`<$>,", "@J$j" },
  { 0x0000, "JSZj", "@@V" },
  { 0x0000, ",=Z", "@@V" },
  { 0x0000, "JK^", "@Dj" },
  { 0x0000, "J<$>,`then`V", "@$,j" },
  { 0x0000, ",J<$>,[XYVUZE]", "(J$)" },
  { 0x0020, "j~<TvxyZEUVXYJf>[,C]~[vUVXY]", "&$j" },
  { 0x0000, "jZE", "@NV" },
  { 0x0001, "j<dDK,>[VZ]", "@$V" },
  { 0x0001, "jP<AO#Nw>[VZ]", "@@$V" },
  { 0x0001, "jV<$>C[VZ]", "@@$jV" },
  { 0x0001, "jE", "@V" },
  { 0x0000, "`how`#Z", "@@V" },
  { 0x0012, "~[VXYxy]Z[TOS]", ".V" },
  { 0x0029, "E`itself`", "V " },
  { 0x0000, ",Z[MR],", ",VM" },
  { 0x0000, "[VZ]R<D>P", "VM" },
  { 0x0000, "B[VZ]R", "BVM" },
  { 0x001C, "B[RM]~V", "PM" },
  { 0x001F, "P[MR]", "PM" },
  { 0x0000, "PSR", "PM" },
  { 0x0027, "V<P>R~[KVXYUB]", "@$M" },
  { 0x0000, "GR~[UVXY]", "GM" },
  { 0x0000, "BS", " M" },
  { 0x0000, "[PV]S[bB*]", ".M" },
  { 0x0000, "[BC]AV", ".DV" },
  { 0x0000, "BK<D>Z", "BK$V" },
  { 0x0000, "B<VAON>,Z", "B$,V" },
  { 0x0005, "V<MTAONw\"'K>BXE", "V$b V" },
  { 0x0000, "v<(#?)>B[VZ]", "@$bV" },
  { 0x0007, "[VZ]BY", "Vb" },
  { 0x0007, "[VZ]<({}#)>B<dD\"'>[VZ]", "V$b$V" },
  { 0x0007, "VBY[VZ]", "Vb V" },
  { "V<SRMTAO#Nw\"K>B<D\">[VXYZ]", "", 0x0006 },
  { 0x0008, "E<SRMTAO#Nw\"K>B<D\">[VXYZ]", "@$b" },
  { 0x0029, "[EV]<TAO>[#N]Z", ".$.V" },
  { 0x0008, "E[RM][VZ]", "@MV" },
  { 0x0008, "G<RMTNw\"K>B[VXYZ]", "@$b" },
  { 0x0009, "V<dD>G", "@$V" },
  { 0x002A, "ZG", "VV" },
  { 0x000D, "NB[VZ]", "@bV" },
  { 0x000B, "X<TAO>N[XV]", " " },
  { 0x0018, "p<RTPAOdDNGFE?#+,>[VUXY]", "J" },
  { 0x0000, "IGI", "IA" },
  { 0x0013, "I<#>GN", "I$N" },
  { 0x0013, "AG", "@N" },
  { 0x0000, "SGP", "ON" },
  { 0x001E, "PG<TAONw>[C,]G", "" },
  { 0x001E, "P<KdD#?>G", "" },
  { 0x0013, "[jQ]<Nw#>G", ".$N" },
  { 0x0012, "NGJ", "NN" },
  { 0x0000, "G`that`", "GJ" },
  { 0x0000, "GR`that`", "GMJ" },
  { 0x000A, "[ZV]<MNw>`that`", "V$J" },
  { 0x000A, "E<Nw>`that`", "V$J" },
  { 0x0032, "[NZ]`that`<RKdD>[VUXY]", "NL" },
  { 0x0032, "w`that`<RKdD>[VUXY]", "wL" },
  { 0x0032, "N`that`<RKdD>[EZ]", "NL$V" },
  { 0x0014, "N<wAE?#\"'(>`that`", "N$L" },
  { 0x0015, "`that`[RT:O]", "J" },
  { 0x0000, "[NZ]<w\"'(?)>`who`", "N$L" },
  { 0x0025, "[NZ]<P(w#?H,\")>`which`", "N$L" },
  { 0x0000, "`which`<KdD>[XYUVR]", "L" },
  { 0x0000, "[,N]<w>`whose`<AO>[NZ]", ".$l$N" },
  { 0x0000, "L<ANw>BZ", "L$BV" },
  { 0x0000, "[lL]<N>G", ".$N" },
  { 0x0000, "LT", "Lt" },
  { 0x0000, "~PLZ", ".LV" },
  { 0x001D, "~PL<,TPHAONw?\"'#>E", ".L$V" },
  { 0x001D, "~PQ<dD?#>E", ".Q$V" },
  { 0x0000, "[Sk]<dD?#>E", ".$V" },
  { 0x0000, "J[N#?]E", "J.V" },
  { 0x0024, "[RL]`like`", ".V" },
  { 0x0000, "LV<$>C`that`V", "@@$CL" },
  { 0x0000, "VSZ", "@ON" },
  { 0x0003, "VS<GE>N", "@O" },
  { 0x0022, "SZ", "SV" },
  { 0x0000, "YNG", "YNg" },
  { 0x0000, "`who`<dD>Z", "@$V" },
  { 0x0000, "Q<#>Z", "Q$N" },
  { 0x0000, "[g+]Z", ".N" },
  { 0x0000, "N`where`", "NJ" },
  { 0x0000, "XA`that`", "XAJ" },
  { 0x0000, "T<AO>?~C", "T$N" },
  { 0x0013, "[TtOH\"]G", ".N" },
  { 0x0011, "A-E", "D A" },
  { 0x0011, "N-E", "@@A" },
  { 0x0011, "E-[NZ]", "A-N" },
  { 0x0011, "T<A>E", "@$A" },
  { 0x0011, "PLE", "@@A" },
  { 0x0011, "A[,C]E", "@.A" },
  { 0x0000, "P[#N]BZ", "@.BV" },
  { 0x0000, "B<KdD>Z", "@$V" },
  { 0x0000, "MCZ", "@@V" },
  { 0x0000, "V`open`", "@A" },
  { 0x0000, "V`fine`", "@D" },
  { 0x0000, "V`free`", "@D" },
  { 0x0000, "(Zd", "@V" },
  { 0x0000, "ZdT", "V" },
  { 0x0000, "NZQ", "@V" },
  { 0x0010, "Q<TAOIH?#>N<Nw>Z~<VXYZ>[j*]", "@$N$V" },
  { 0x0010, "Q<TAOIH?#>N<Nw>Z<dD>[j*]", "@$N$V" },
  { 0x0010, "J<TAOIH?#>NZ~<VXYZ>[j*]", "@$NV" },
  { 0x0010, "J<TAOIH?#>NZ[BP]", "@$NV" },
  { 0x0023, "N<\"'>P<AOIHNw?#>Z~<VXYZ>[,j*]", "@$P$V" },
  { 0x000E, "I<P>NZ", "@$NV" },
  { 0x0023, "TN<PAOIHNw?#>Z[,Cj*]", "@@$V" },
  { 0x000E, "[bB]V<PTAOHINw?#>[,C]<dDK>Z", ".V$.$V" },
  { 0x001A, "V<\"'PNw>[,C]<\"'KdD>[EG]", "@$.$V" },
  { 0x0020, "V<\"'>[,C/]<C\"'KdD>[EGZ]", "@$.$V" },
  { 0x0000, ",`so`~[,C*]", "@J" },
  { 0x0000, "B/P", "P/P" },
  { 0x0000, "A/N", "A/A" },
  { 0x0013, "G/N", "N" },
  { 0x0000, "`having`E", " F" },
  { 0x0000, "N<wD>E[XYUV]", "@$W" },
  { 0x0000, "N<w>E,~[EC]", "@$W" },
  { 0x0000, "N`being`A[+&,C*]", "@ W" },
  { 0x0000, "N<wdD>`being`E", "@$ W" },
  { 0x0011, "J`being`E", "  A" },
  { 0x0000, "MPR", "MJR" },
  { 0x0000, "V,C~V", "@^" },
  { 0x003A, "N~<BVXUY>[^xyXYV*]", "" },
  { 0x003B, "[xyXY]~<BbVXUY>[^jJLlQ*]", "" },
  { 0x0000, "Z", "N" },
  { 0x0000, "S<aA\"'>N", "O" },
  { 0x0000, "N<w>[C&,]G[C,&L*]", "N$&N" },
  { 0x0013, "[,&C]N[,&C]G~M", ".N.N" },
  { 0x0013, "[bB]VG", ".VN" },
  { 0x0030, "p~L", "P" },
  { 0x0000, "d<A>[N#]", "A" },
  { 0x0000, "N<Hw>\"<TAO>N<P/NAOw>\"", "@$+" },
  { 0x0000, "\"T", "@^" },
  { 0x0000, "T*", "#" },
})

table.insert(rules, {
  { 0x00, "V~<VXUY>[^BbjJLlQ*]", "" },
  { 0x3C, "X`need`", " `xпонадобится`" },
  { 0x0B, "`there`X", " x" },
  { 0x0B, "V`below`T", "@P" },
  { 0x00, "R<K>x", "m" },
  { 0x00, "RXKx", "m " },
  { 0x00, "p[*)]", "D" },
  { 0x0B, "B<?>*", "P" },
  { 0x0B, "*B[:*]", "@`Dдля`" },
  { 0x0B, "NI!мес!", "A" },
  { 0x00, "V<TAO>NG", "@$NF" },
  { 0x2C, "[gG]<TAONw>CG", "g$Cg" },
  { 0x0B, "VGT", "@g" },
  { 0x0B, "N[,C]G[,C*]", "@.N" },
  { 0x00, "GU", "N" },
  { 0x00, "CNG*", "@@N" },
  { 0x0B, "(G)", "@N" },
  { 0x00, "VwG", "" },
  { 0x2E, "*G<A>[#N]", "" },
  { 0x2E, "N[C/]G", "" },
  { 0x2E, "[*jJ]<TAO>N<NwK>E*", "" },
  { 0x09, "*~<xyUVXYE>G~<xyUVXY>[;*]", "" },
  { 0x2D, "A`for`G", "" },
  { 0x2F, "*G~<xyUVXY>[L;*]", "" },
  { 0x2F, "[*Jj]<CD>G<dDK>[UVXY]", "" },
  { 0x2F, "d<A>[N#]", "A" },
  { 0x00, "N<\"'#>N", "A" },
  { 0x35, "DNCA", "@A" },
  { 0x35, "TN<\"'>[#?]", "@A" },
  { 0x35, "X<D>N<D>[,&Jj*]", "@$A" },
  { 0x35, "[,TPV()]N<,>C<D>AN", ".A" },
  { 0x36, "[TP]N,<adD>A~P", ".A" },
  { 0x35, "NC[EA][,Jj*]", "A" },
  { 0x35, "[AOH][,C&(\"']N<)\"'>N", "..A" },
  { 0x35, "*`no`,RXK*", "@y    " },
  { 0x0B, "*S`is`BV", "@ `Uследует`" },
  { 0x0B, "BV~<,CRSLJ>XB", "@@$Xb" },
  { 0x0B, "[VXY]~<Jj|^>`is`BV", ".$ `Uдолжен`" },
  { 0x0B, "`as`<dD>E[,;PBd*]", "" },
  { 0x04, "J<dDK>E<D>[,CPBd*]", "" },
  { 0x04, "JE`as`", "" },
  { 0x04, "J<dD>E<D>[,C]AP", "" },
  { 0x38, "G<dD>`with`", "F" },
  { 0x00, "~JE<dD>`by`~H", "" },
  { 0x03, ",E<dD>`as`", "" },
  { 0x03, "E<dD>`with`", "" },
  { 0x03, "[VXY*]P<TDdAO>N<dDwW,C>E<,CEFdD>[NP(:*]", "" },
  { 0x30, "[UW]~<UVXY>E<,CEdD>[FPJ]", "" },
  { 0x30, "EU", "" },
  { 0x30, "E[,C]<E,C>[FA]", "" },
  { 0x30, "E", "" },
  { 0x0A, "G", "" },
  { 0x08, "V<TAONw>`so`~[,C*]", "@$`J1так, чтобы`" },
  { 0x06, "N`come`P", "@V" },
  { 0x0B, "`find`<DMTNO>A", "`Vсчитать`" },
  { 0x15, "N<w>`of``whom`", "@$`pиз``L, который`" },
  { 0x0B, "N<D>`in``use`", "@$`Aприменяемый` " },
  { 0x0B, "V<A>`copy`", "@$`Nкопия`" },
  { 0x00, "H`may`", "@N" },
  { 0x00, "N`number`", "@`Nномер`" },
  { 0x22, "`number``of`<TAO>N", "`Nномер`" },
  { 0x05, "[*,:;(\"]<D>`see`", ".$`Vсмотри`" },
  { 0x0B, "O<ADHI>`letter`", "@$`Nписьмо`" },
  { 0x00, "[HI]`and``a``half`", ".  `Aс половиной`" },
  { 0x00, "U<KD>`like`", "@$`Vнравиться`" },
  { 0x0B, "`it`[,C*]", "`Rэто`" },
  { 0x00, "`about``it`[,C*]", "`PПоб``этом`" },
  { 0x00, "MR", "" },
  { 0x06, "V`as`", "@D" },
  { 0x22, "K`as`A`as`", " `Dне так`A`Jкак`" },
  { 0x0B, "`as``much`<TPAONw?#>`as`", " `iстолько`$`iсколько`" },
  { 0x0B, "*`as`<$>[UVXY]<$>;", "@`Jпоскольку`" },
  { 0x0B, "[,*]`provided`<TAO>[N*]", ".J" },
  { 0x0B, "*`since`", "@`Jпоскольку`" },
  { 0x0B, "[j*]<dD,>`be``sure`", ".$ `Vубедитесь`" },
  { 0x2A, "*P<N>`be``sure`", "@@$ `Vубедитесь`" },
  { 0x2A, "X`firm`", "@A" },
  { 0x0B, "V`most`[,*]", "@D" },
  { 0x00, "V`second`[*)]", "@D" },
  { 0x00, "H`percent`N", "@`Aпроцентный`" },
  { 0x00, "H`times`", "@`Dраз`" },
  { 0x00, "*`here`X", "@`yвот` " },
  { 0x0B, "*`let``us`", "@`vдавайте`b" },
  { 0x17, "`let`M[ZVNG]", "V@V" },
  { 0x00, "\"`no`\"", "@K" },
  { 0x0B, "`no`[,C*]", "K" },
  { 0x00, "K[,C*]", "`нет`" },
  { 0x00, "`a``while`", " D" },
  { 0x0B, "[C&]K[&*]", ".D" },
  { 0x0B, "[TNV]`default`<?#>N", ".A" },
  { 0x00, "Y`others`V", "`Vпозволять`M" },
  { 0x0B, "`to`Y~<XYV>`do`", "J $V" },
  { 0x1A, "j`then`", "@j" },
  { 0x0B, "`if`<$>,`then`", "@$,j" },
  { 0x0B, "`on``whether`<$>`or`", " `Jили`$&" },
  { 0x0B, "`either`~<,>`or`", "`Cили`$`Cили`" },
  { 0x00, "`in``either`<$>`or`", "`Pкак в` $`Cтак и`" },
  { 0x0B, "`both`~<RXYUVB>`and`", "`Dкак`$`Cтак и`" },
  { 0x0B, "`both`<$>,`and`", "`Dкак`$,`Cтак и`" },
  { 0x0B, "`under``both`<$>`and`", "`Pкак под` $`C, так и под`" },
  { 0x0B, "~[bB]V[C,]<CKdD>V", "" },
  { 0x07, "~[bB]V~<j>[C,]<KdD>V", "" },
  { 0x07, "JR[XYUV]<TAON>R", "" },
  { 0x02, "VP<TAO>N<w>A", "" },
  { 0x01, "NP<T>NN`of`", "" },
  { 0x02, "[#N]<w>[SO]", "" },
  { 0x01, "`give`[#N]<w>[AN#?]", "" },
  { 0x01, "[#N]<w>T", ".$t" },
  { 0x25, "*<dDJ,>E[A\"N]", "@$A" },
  { 0x0B, "*ECE[A\"N]", "@ACA" },
  { 0x0B, "[GVIH\"J]E[AN]", ".A" },
  { 0x00, "~VTNI", ".TA" },
  { 0x00, "S<D>[AOIH]", "O" },
  { 0x00, "J~<|J>[VUXY]", "" },
  { 0x0F, "Jry", "@@x" },
  { 0x10, "uE", "@V" },
  { 0x13, "[NR]ET", ".V" },
  { 0x18, "[SR]<dDK>v", "M" },
  { 0x1F, "IA", "A" },
  { 0x29, "As[X,*]", "@ " },
  { 0x0B, "S<AO>N", "O" },
  { 0x0B, "FPN~<UVXYR>[UVXY]", "" },
  { 0x3A, "*<Dd,>[IAOTPN]~<VXY>[RSJLlj|^(xyGBUXYV*]", "" },
  { 0x32, "[U()]~<VXY()>[V^()*]", "" },
  { 0x31, "[VXYxy^]~<VXY>[^J(*]", "" },
  { 0x31, "[fvyGXYV]~<EVXY>[RSJLlj|^xyEBUXYV*]", "" },
  { 0x33, "&<,CdDE>J", "" },
  { 0x33, "PNCN*", "@@&" },
  { 0x00, "ACA", "@&" },
  { 0x00, "[|j]NC<AO>N", ".@&" },
  { 0x00, "`hope`RV", "" },
  { 0x0D, "VRB[VXY]", "" },
  { 0x2B, "V<TAO>N<w>B[VXY]", "" },
  { 0x2B, "[VXYE]<TAOdDNw>x", ".$A" },
  { 0x0B, "BVMBV", "" },
  { 0x39, "xB", "@b" },
  { 0x0B, "`like`B", "@b" },
  { 0x0B, "H)<K>B", "@@$b" },
  { 0x00, "CB", "@b" },
  { 0x00, "BP", "b" },
  { 0x00, "QB", "@b" },
  { 0x0B, "N<KkdD>B", "@$b" },
  { 0x21, "d<PM>B", "@$b" },
  { 0x27, "*<dD,>[JB]V", "" },
  { 0x0D, "VbV", "" },
  { 0x0E, "VR[*b]", "@M" },
  { 0x0B, "a[|*]", "D" },
  { 0x0B, "[(:;j*]<KDd>YT", ".$V" },
  { 0x00, "[(:;j*]<KDd,>V", "" },
  { 0x1D, "~VVP[,*]", "@@p" },
  { 0x0B, "N<w>P*", "@$p" },
  { 0x0B, "PL", "p" },
  { 0x00, "NX*", "@ " },
  { 0x0B, "NF*", "@W" },
  { 0x0B, "PNDE*", "@@@W" },
  { 0x0B, "[TCP]<A>NE[(*]", ".$NW" },
  { 0x0B, "[TC]Nd[:;j|UB(*]", ".NW" },
  { 0x23, "N<w,>d~[KUVXYEF*]", "@$A" },
  { 0x23, "NX`on`*", "@ `Vвключать`" },
  { 0x1C, "(`at`<Dd>)", "@D" },
  { 0x00, "(<#PIHA,CdD>)", "{$}" },
  { 0x00, "#:", "@#" },
  { 0x00, "\"<TAO-?#>N<N-w:>\"N[*P,C]", "" },
  { 0x20, "b[TAON#]", "`Pк`" },
  { 0x3E, "b[SRM]", "`Pк`M" },
  { 0x3E, ";~<UVXYR>[J*]", "&" },
  { 0x0C, "[*|;j,C]`it`<KdD>V[*J]", ".J" },
  { 0x1E, "B<KdD>V", "" },
  { 0x24, "aN", "i" },
  { 0x00, "XRU", " " },
  { 0x0B, "X<K>x", " " },
  { 0x0B, "P`her`[,C&:;P*]", "@M" },
  { 0x00, "`her`[,TAODdC&:;P*]", "M" },
  { 0x00, "[RN#]`used``to`[GVE]", "@@ V" },
  { 0x42, "Xd[Bj]", "@A" },
  { 0x00, "X", "" },
  { 0x12, "n", "N" },
  { 0x1B, "g", "G" },
})

table.insert(rules, {
  { 0x00, "Q`is``the`", "@  " },
  { 0x0B, "`what`X~<EG>[,*]", "" },
  { 0x00, "`is`~<RS>`correct`*", " $A" },
  { 0x00, "`is`[RS]`correct`*", " .D" },
  { 0x00, "`is`<$>Z*", " $N" },
  { 0x00, "`is`<$>Z[Bb]", " $Nb" },
  { 0x01, "X<TAODNPRSw>[eZV]", " $V" },
  { 0x01, "X<TAONRmSw>x", " " },
  { 0x08, "[XY]<KTAO>N[eE]", "" },
})

table.insert(rules, {
  { 0x02, "P<$>N" },
  { 0x00, "P<$>[#?O]" },
  { 0x14, "OP<$>N" },
  { 0x15, "O<A>N" },
  { 0x0C, "Q<AO?\">N" },
  { 0x12, "P<AOdDwc&>[IH]" },
  { 0x12, "P<AOdDNw>&<AO>[IH]" },
  { 0x00, "H-H" },
  { 0x00, "N-N" },
  { 0x00, "PA" },
  { 0x06, "N<AOD(?)w#'\">[NH]" },
  { 0x06, "i<AOD?#'\">N" },
  { 0x04, "F<&D>F" },
  { 0x10, "FN" },
  { 0x05, "EN" },
  { 0x10, "F~<P>N" },
  { 0x05, "E~<P>N" },
  { 0x16, "G<$>N" },
  { 0x07, "N<Hw>&<&AOD#?\"'>N" },
  { 0x00, "#&<AOD>N" },
  { 0x07, "N<w>(<AOD>N" },
  { 0x00, "N<Hw>/N" },
  { 0x11, "N<w{}#HDK&>[EA]" },
  { 0x04, "[AO]<AO#\">[?#N]" },
  { 0x04, "[AO]~<PHI>N" },
  { 0x01, "I<AO?\"H{}>N" },
  { 0x0D, "H<AOD(?#)\">N" },
  { 0x04, "[AO]<AO#\">[HI]" },
  { 0x0B, "[GE]M" },
  { 0x04, "[AOE]<&D>[EA]" },
  { 0x0E, "O[&c]I" },
  { 0x03, "U<KD>[VX]" },
  { 0x0B, "VM" },
  { 0x13, "V[,C]<C>V" },
  { 0x17, "PM" },
})

table.insert(rules, {
  { 0x0C, "J[VUXY]" },
  { 0x0C, "J~<|J>[VUXY]" },
  { 0x0C, "O[UV]" },
  { 0x0C, "JE" },
  { 0x0C, "JEC[EA]" },
  { 0x31, "[RN]x" },
  { 0x23, "J<ryV>NR" },
  { 0x36, "~[LlJQGRBb]N<P>R" },
  { 0x36, "UPR" },
  { 0x35, "PRY*" },
  { 0x37, "[VXY]N[N#][UVXY]" },
  { 0x38, "[UV][kNR][VXY]" },
  { 0x3F, "L[RN]<$>p*" },
  { 0x25, "~[bB]?[UVXY]" },
  { 0x2B, "EA" },
  { 0x2D, "E<p>[NW]" },
  { 0x17, "ry" },
  { 0x01, "[kNRSQ]<EFP,L>[UVXY]" },
  { 0x01, "N,<$>,[UVXY]" },
  { 0x01, "NPC[UVXY]" },
  { 0x01, "[kNRSQ](<$>)<K>[UVXY]" },
  { 0x3E, "Nv" },
  { 0x22, "#<,EP>[UVXY]" },
  { 0x01, "NBN[UVXY]" },
  { 0x01, "NLU[UVXY]" },
  { 0x01, "NL<XAP>,V" },
  { 0x01, "NL<NUCV,>bNV" },
  { 0x02, "[BbUV]<pP>[NW]" },
  { 0x03, "[BbV]<NI>P" },
  { 0x1C, "Y[NW]" },
  { 0x19, "[yXYU]<NIA>P" },
  { 0x19, "[XY]PP" },
  { 0x0F, "Yk" },
  { 0x09, "[UV]k" },
  { 0x1E, "[OIHW]<,EP>[UV]" },
  { 0x1E, "[OIHW](N)<,>[UV]" },
  { 0x45, "[IW][XY]" },
  { 0x05, "[NP]<,DC>[EF]" },
  { 0x1F, "[OIHW]<,C>[EF]" },
  { 0x21, "[IHW]<pP,>[Ll]" },
  { 0x44, "N([SA]" },
  { 0x16, "N<pPE,XO>L" },
  { 0x07, "[SP]<p,>[lL]" },
  { 0x07, "Nl" },
  { 0x1A, "pL" },
  { 0x2F, "[IHO]p" },
  { 0x30, "Np" },
  { 0x1C, "pN" },
  { 0x11, "X<k>N" },
  { 0x1B, "[xyf][NW]" },
  { 0x24, "UXA" },
  { 0x12, "X<k>A" },
  { 0x2A, "X[SO]" },
  { 0x04, "[VB]<p>[AE]" },
  { 0x0B, "UE" },
  { 0x06, "R,E" },
  { 0x06, "U[AF]" },
  { 0x0E, "[BUVY][IOH]" },
  { 0x10, "LV[NP][UVXY]" },
  { 0x10, "L<P>[VXYU]" },
  { 0x20, "[NP]L[NR]" },
  { 0x1D, "LVN" },
  { 0x13, "[GEF]P" },
  { 0x13, "[GEF]PP" },
  { 0x08, "U<A>[,C]<C>V" },
  { 0x15, "V<#>[,C]U" },
  { 0x15, "V<$>,C[UY]" },
  { 0x18, "U<N>,CU" },
  { 0x18, "XACU" },
  { 0x0A, "V<NWP>[,C]<C>V" },
  { 0x17, "YN[C,]V" },
  { 0x18, "Y[NW],CY" },
  { 0x27, "ry<$>C[YV]" },
  { 0x18, "YN[C,]U" },
  { 0x0D, "U<P>CE" },
  { 0x2C, "ECE" },
  { 0x2E, "QB" },
  { 0x3C, "[RN]u" },
  { 0x3C, "lN" },
  { 0x46, "NlRV" },
  { 0x3B, "[NR]UV" },
  { 0x3B, "[NR]Vb" },
  { 0x3D, "MvP" },
})

return rules